### ISSUE TITLE
CIFS support

### ISSUE THREAD

**Issue by lasley** [OCA/connector-cmis#11]
I am about to be starting a project for a CIFS/SMB connector, which seems to have a lot of overlap with this CMIS module. 

I'm wondering if it would make sense for me to instead create a backend adapter/import logic for CIFS adhering to the existing interface for inclusion here instead. 

It seems like we would have a bit of a naming conflict, but I feel that we will be duplicating a lot of file handling logic if we start making independent repos for all of the different file systems. Long-term, I would also like SFTP and WebDav support in my Odoo as well.

Anyone have any thoughts on this? I noticed @max3903 created oca/web#338 which seems that the community goals may be aligning with mine here.

~~@lmignon - What is the status of your project that is going to be utilizing this?~~ I should check PRs more

Apologies if creating an issue was not the way to gather responses on this.

**Comment by lmignon** [comment]
@lasley 
We develop a complete new solution to integrate Odoo with a cmis backend. Our solution is based on:
- A new widget that let's you browse a cmis backend from within Odoo,
- A new abstract model used to link an Odoo Object to a cmis:folder,
- A new Wizard to batch process documents from a cmis:folder to link with an object in Odoo (a kind of document reconciler..)
- ....
  The developpent of all these stuff has started for months and since the concepts, the approach and the API become stable we are now able to provide a first preview of the new widget https://www.youtube.com/watch?v=TK49kl0Viyk
  The solution is developed on Odoo Community and compatible with Odoo enterprise.

**Comment by max3903** [comment]
@lasley an issue is the right place to start the conversation and I think
it is the right repository for your work.

In the long run I have no problem renaming the repo to host your CIFS
connector. We could also host other modules like connector_file and every
module related to file transfer...

**Comment by lasley** [comment]
@lmignon - This is great! The document feature is way beyond what we were planning - I love it. Am I correct that these concepts can be applied to SharePoint as well, as it conforms to CMIS for the most part?

@max3903 - Excellent, sounds like we're on the same page then. 

One potential issue I see with combining the interfaces into one repo is in terms of dependencies. IIRC Odoo requires that all the Python dependencies are installed for any installable modules in the DB. Is there any sort of strategy for mitigating this? We definitely don't want to force someone to install CIFS in order use CMIS, and vice-versa.

**Comment by Ehtaga** [comment]
@lmignon Hi Laurent, is your module already on GitHub?

**Comment by lmignon** [comment]
@lasley 

>  Am I correct that these concepts can be applied to SharePoint as well, as it conforms to CMIS for the most part?

You're right, CMIS is a standard supported in theory by SharePoint, Nuxeo, Alfresco and ???
At this stage we only have tested the new addons with Alfresco but the code is designed  to provide a base addon providing standard CMIS based functionalities and we have developed specialized addons to leverage the user experience by providing extra features specifics to a CMIS implementation. For exemple in the video, all the functionalities are provided by the base addon (named at this stage web_cmis_viewer) but the direct link to open the content in alfresco is provided by a specialized module 'web_cmis_viewer_alf'). We try to take care of designing the interfaces (JS and Python) to be easily extendable. 

@Ehtaga The code is not yet available but we hope to release it as soon as possible once the code and a first set of functionalities will be stabilized.

**Comment by lasley** [comment]
@lmignon - 

Awesome; we have a few customers that would love this functionality in their SharePoint. I am looking forward to the completion of your project so that we can begin expanding upon it 😄 

I'll hold off on my planning, as I would like to see the structure you come up with & this isn't a blocker towards current deadlines. Will keep an eye out for your PRs, and will provide some thoughts on the existing ones soon

**Comment by lasley** [comment]
Closing ticket - plan accomplished I do believe. Once things progress a bit further, we can start talking about repo naming, dependencies, etc. Thanks everyone!
