### ISSUE TITLE
[7.0] "CMIS connection error" with Alfresco 5.1

### ISSUE THREAD

**Issue by max3903** [OCA/connector-cmis#13]
# Versions

7.0
Not tested with later versions.
# Steps to reproduce
- Install Alfresco CE v 5.1
- Create a user and set his password
- Test the CMIS URL and credentials: http://localhost:8080/alfresco/api/-default-/public/cmis/versions/1.0
- In Odoo, configure a CMIS backend with the URL above and the credentials
- Save the backend and click on "Test Directory"
# Result

```
OpenERP Warning
CMIS connection Error!

Check your CMIS account configuration. 
```
# Expected result

`Connection successful`

**Comment by lmignon** [comment]
@max3903 In 5.1, The cmis:path of a cmis:folder is a list. (may be to support smart folders)

**Comment by max3903** [comment]
@lmignon Thanks for the info. What if the CMIS backend is not Alfresco and does not return a list? What does the CMIS specification say? Do we need to be software-specific?

ping @ehdem

**Comment by lmignon** [comment]
@max3903 both are supported https://github.com/acsone/connector-cmis/commit/61c86c8f4b69b9e72eed847b418b6e8f2cb6f6d1#diff-4926d421abe6320af51103077b26acffR101
Accoring to the specification, the `cmis:path` should be a String http://docs.oasis-open.org/cmis/CMIS/v1.1/CMIS-v1.1.html#x1-550002

**Comment by lmignon** [comment]
@hbrunn I've improved the check in a branch with a lot of improvements https://github.com/acsone/connector-cmis/commit/9444344e3fffb1d1494b1ae333e9e907d3121e32

**Comment by max3903** [comment]
@lmignon I backported your change in #14 but I still have the same error message.

**Comment by lmignon** [comment]
@max3903 strange.. At this stage only a debug session can help to understand what's the problem.

**Comment by max3903** [comment]
@ehdem can you help?
