### ISSUE TITLE
need connecter module

### ISSUE THREAD

**Issue by LakshminarayananOKN** [OCA/connector-cmis#19]
while installing this cmis module in odoo 10, required connector module where is that connector module?

**Comment by lmignon** [comment]
@LakshminarayananOKN This module is not yet ported in 10.0. A PR (#18) exists for the cmis module only. The cmis module no more depends on `connector` and is the minimal foundation on which all cmis modules can be build. It's one of the basic pieces of the **alfodoo** addons (https://github.com/acsone/alfodoo, http://www.alfodoo.org)

**Comment by LakshminarayananOKN** [comment]
thanks @lmignon finally done it in odoo 9 thanks a lot
