### ISSUE TITLE
This cmis Module work fine in odoo 10?

### ISSUE THREAD

**Issue by LakshminarayananOKN** [OCA/connector-cmis#21]
i have already implemented alfodoo in odoo 9 and also i need to implement alfodoo in odoo 10. so this cmis connecter working in odoo 10?

**Comment by lmignon** [comment]
@LakshminarayananOKN The port to Odoo 10 is done in https://github.com/OCA/connector-cmis/pull/18

**Comment by LakshminarayananOKN** [comment]
**cmis** module depends module **connector** , there is no connector module then how can i implement it?

**Comment by lmignon** [comment]
@LakshminarayananOKN In #18 and since 9.0 cmis no more depends of **connector**

**Comment by lmignon** [comment]
#18 is now merged. **cmis** addon is now available on Odoo 10.0 (cmis_read, cmis_write remains unported)
