### ISSUE TITLE
CMIS integration model

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/connector-cmis#5]
Hello,

I have been throroughly testing the cmis and cmis_write functionality, and unless I am mistaken, I can see a fundamental flaw in the "cmis_write" model.

When a document is attached to an object, "cmis_write" will create the document in the DMS, in a static folder location defined in the cmis backend configuration in Odoo. As you keep attaching documents in Odoo, the same DMS folder starts to be packed with files coming from multiple resources in Odoo.

But DMS systems such as Alfresco do not allow two files with the same name to be held in the same folder! 

As a consequence, if you want to use the DMS as your external respository for Odoo, seems to me that you should name each file as resource model + resource id + filename. A user accessing to the DMS would be confused about this approach.

The other option would be to create each entity in Odoo as a separate folder in the DMS.

I am currently evaluating a different model. Sync only static directories in "document_directory" and the associated files instead.

As soon as a static directory is created or changed in Odoo, if it is flagged as 'Sync with DMS', the directory and underlying content (other directories and files) are synced with the DMS.

Static directories are created in Odoo for each resource by default, in order to ensure proper syncronization. An resource can have 0 to 1 associated static directories, that can in turn be synced with the DMS or not.

A user can attach a document to an object in Odoo, but unless the document specifies a directory that in synced directory, it won't be synced with the DMS.

A scheduled job in Odoo regularily compares and aligns the synced directories with the corresponding DMS folders.

As a consequence, if a file is moved by a user in the DMS from one folder to another, in Odoo the file will be moved to the new directory, and also to the new resource.

You can access here to a prototype:
https://github.com/Eficent/eficent-project-knowledge

Install all modules and start creating projects and subprojects. 
- For each project a corresponding static folder is created in Odoo and in the DMS. 
- All files attached to the project are also attached to the folder in the DMS. 
- If you change the directory in a file in Odoo to a different project directory, the resource associated to the file also changes to that associated to the destination directory.

Regards,
Jordi.

**Comment by max3903** [comment]
The current module implements a scenario where the DMS is taking care of sorting/classifying files in directories based on metadata.

Based on the policy configured/programmed in the DMS, if we have a collision, it means that the file is a new revision of the same document and this should be handled by the DMS.

If you want to manage the sorting/classifying policy in Odoo, you can extend our module. Have a look at this blueprint: https://blueprints.launchpad.net/knowledge-addons/+spec/allow-dms-storage-on-a-per-model-basis

**Comment by JordiBForgeFlow** [comment]
Thanks @max3903. 

I realized that for my use case replicating the documentation up and down would be too complex. I am implementing an alternative approach, consisting to create, for each project, an static folder, that is then replicated to the DMS as a folder.

Then, the user can jump from the project in Odoo to the DMS using an URL associated to the project folder.

At the end, seems to me that a DMS such as Alfresco manages very well documentation, and the only benefit I am seeing in the integration is moving the project work breakdown structure, and possibly additional metadata.

You can see here a prototype:
https://github.com/Eficent/eficent-project-knowledge
