### ISSUE TITLE
Migration to version 8

### ISSUE THREAD

**Issue by max3903** [OCA/connector-cmis#6]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-8
# Modules to migrate
- [ ] cmis
- [ ] cmis_read
- [ ] cmis_write

**Comment by ezerouali** [comment]
Any progress?
Do you still need help?
I have some work already done.

**Comment by max3903** [comment]
Hello @makwin,

No progress has been made on version 8. On later version, you may want to talk to @lmignon or @sbidoul.

Which modules have you migrated to version 8? I can create the 8.0 branch so you can make your pull requests if you want. Just let me know.
