### ISSUE TITLE
Migration to version 9

### ISSUE THREAD

**Issue by max3903** [OCA/connector-cmis#8]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9
# Modules to migrate
- [x] cmis by @lmignon #15 
- [ ] cmis_read 
- [ ] cmis_write

**Comment by lmignon** [comment]
@max3903 I'm working on a new project in 9.0. Part of this project will use some functionalities provided by the cmis connector and we also plan to add new ones. Nevertheless the 8.0 and 9.0 branches have disappear from git.  How can we process to manage the required migration from 7.0 to 9.0? (I want to avoid a too expensive 2 steps migration process 7.0 -> 8.0 8.0 -> 9.0)

**Comment by max3903** [comment]
@lmignon I don't think they were created. If you want to create the 9.0 one and start working on it, please be my guest.

**Comment by lmignon** [comment]
OK thank you @max3903

**Comment by lmignon** [comment]
@yvaucher I suppose that You've done the same mistake as me by closing this issue?

**Comment by pedrobaeza** [comment]
You can use https://github.com/OCA/maintainer-tools/blob/master/tools/migrate_branch.py

Are you aware of it?

**Comment by lmignon** [comment]
@pedrobaeza Thank you for the tip.
@max3903 The branch 9.0 is created. 
@max3903 @pedrobaeza I don't have the required privileges to make it the default one as described in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0#initialization-already-done-in-oca.

**Comment by pedrobaeza** [comment]
9.0 branch made default

**Comment by max3903** [comment]
and protected :)

**Comment by yvaucher** [comment]
@lmignon I didn't touch it, it seems someone moved the card on Waffle.io I guess
